server:
  port: 8089

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: herald-proxy
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

herald:
  auth:
    cookie-name: herald_auth
    max-age-days: 30
    secret-b64: MOeBPzJq5YNy4v2f+3FIeh1bNOGwhEg/McianDiH1GU=
  llm:
    proxy:
      http-log:
        enabled: true          # master switch
        log-bodies: true       # osobny kill-switch na body
        max-body-chars: 1000000000    # utnij logi, bo LLM potrafi być gadułą
        log-headers: true
        only-errors: false      # jak true -> loguj tylko >=400

jira:
  baseUrl: ${JIRA_BASE_URL:http://localhost:8080}
  projectKey: ${JIRA_PROJECT_KEY:HRLD}
  apiVersion: ${JIRA_API_VERSION:2}

feign:
  client:
    config:
      default:
        loggerLevel: FULL  # NONE | BASIC | HEADERS | FULL
        decode404: true

logging:
  level:
    root: INFO